export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_MANY_ITEM = 'ADD_MANY_ITEM';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_ALL_ITEM_CART = 'REMOVE_ALL_ITEM_CART';
export const CART_QUANTITY = 'CART_QUANTITY';
