export const GET_LIST_PRODUCTS_REQUEST = 'GET_LIST_PRODUCTS_REQUEST';
export const GET_LIST_PRODUCTS_SUCCESS = 'GET_LIST_PRODUCTS_SUCCESS';
export const GET_LIST_PRODUCTS_FAIL = 'GET_LIST_PRODUCTS_FAIL';
